import { useEffect, useMemo, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Chess } from 'chess.js';
import { getSocket, createRoom, joinRoom, disconnectChessServer, type TimeControl } from '@/lib/chessServer';

const LIGHT='#dce5d1', DARK='#739552', BG='#07111f', CARD='#0d1b2a', WHITE='#f7f9fc', MUTED='#8ea0b8', ACCENT='#39d98a';
const PIECES:Record<string,string>={p:'♟',r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',P:'♙',R:'♖',N:'♘',B:'♗',Q:'♕',K:'♔'};
const LOCAL_TIME:TimeControl={initial:600,increment:0,label:'10+0'};
export default function GameScreen(){
 const params=useLocalSearchParams<{mode?:string;room?:string;bot?:string}>(); const online=params.mode==='online'; const bot=params.bot==='1';
 const [game,setGame]=useState(()=>new Chess()),[selected,setSelected]=useState<string|null>(null),[history,setHistory]=useState<string[]>([]),[color,setColor]=useState<'w'|'b'>('w'),[roomCode,setRoomCode]=useState(params.room||''),[waiting,setWaiting]=useState(online),[status,setStatus]=useState(online?'Connecting…':bot?'Your turn':'Your turn');
 const [clocks,setClocks]=useState({w:600,b:600}),[timeControl,setTimeControl]=useState<TimeControl>(LOCAL_TIME); const board=useMemo(()=>game.board(),[game]); const legal=selected?game.moves({square:selected as any,verbose:true}).map((m:any)=>m.to):[];
 useEffect(()=>{if(!online)return;const s=getSocket();const onReady=(x:any)=>{setGame(new Chess(x.fen));setClocks({w:x.clocks.w,b:x.clocks.b});setTimeControl(x.timeControl);setWaiting(false);setStatus('Your turn')};const onUpdate=(x:any)=>{setGame(new Chess(x.fen));setClocks({w:x.clocks.w,b:x.clocks.b});setTimeControl(x.timeControl);setHistory(h=>[...h,x.move?.san].filter(Boolean));setStatus(x.checkmate?'Checkmate':x.draw?'Draw':x.check?'Check':x.turn===color?'Your turn':'Opponent turn')};const onClock=(x:any)=>setClocks({w:x.w,b:x.b});const onOver=(x:any)=>setStatus(x.reason==='timeout'?`${x.winner} wins on time`:x.reason==='resignation'?`${x.winner} wins`:x.reason==='draw'?'Draw':`${x.winner} wins`);const onDisconnect=()=>{setWaiting(false);setStatus('Opponent disconnected')};s.on('room-ready',onReady);s.on('game-update',onUpdate);s.on('clock-update',onClock);s.on('game-over',onOver);s.on('player-disconnected',onDisconnect);(async()=>{try{if(params.room){const r=await joinRoom(params.room);setRoomCode(r.roomCode);setColor(r.color);setGame(new Chess(r.fen));setClocks(r.clocks);setTimeControl(r.timeControl);setWaiting(false);setStatus(r.color==='w'?'Waiting for opponent':'Your turn')}else{const r=await createRoom('checkmate-mobile',LOCAL_TIME);setRoomCode(r.roomCode);setColor(r.color);setGame(new Chess(r.fen));setClocks(r.clocks);setTimeControl(r.timeControl);setStatus('Room created — share the code')}}catch(e:any){setStatus(e.message||'Connection failed');setWaiting(false)}})();return()=>{s.off('room-ready',onReady);s.off('game-update',onUpdate);s.off('clock-update',onClock);s.off('game-over',onOver);s.off('player-disconnected',onDisconnect);disconnectChessServer()}},[online,params.room]);
 useEffect(()=>{if(!bot||game.isGameOver()||game.turn()!=='b')return;const t=setTimeout(()=>{const moves=game.moves({verbose:true}) as any[];if(!moves.length)return;const move=moves[Math.floor(Math.random()*moves.length)];const g=new Chess(game.fen());const result=g.move({from:move.from,to:move.to,promotion:'q'});setGame(g);setHistory(h=>[...h,result.san]);setStatus(g.isCheckmate()?'Checkmate':g.isCheck()?'Check':'Your turn')},450);return()=>clearTimeout(t)},[bot,game]);
 const tap=(sq:string)=>{if(game.isGameOver()||waiting||(online&&game.turn()!==color)||(!online&&bot&&game.turn()==='b'))return;if(selected){const move=game.moves({square:selected as any,verbose:true}).find((m:any)=>m.to===sq);if(move){const payload={from:selected,to:sq,promotion:'q'};if(online)getSocket().emit('make-move',{roomCode,move:payload},(r:any)=>{if(!r?.success)setStatus(r?.error||'Move rejected')});else try{const g=new Chess(game.fen());const result=g.move(payload);setGame(g);setHistory(h=>[...h,result.san]);setStatus(g.isCheckmate()?'Checkmate':g.isCheck()?'Check':g.isStalemate()?'Draw':'Bot thinking…')}catch{}setSelected(null);return}}const piece=game.get(sq as any);if(piece&&piece.color===game.turn())setSelected(sq);else setSelected(null)};
 const resign=()=>online?getSocket().emit('resign',{roomCode}):router.back();const draw=()=>online?getSocket().emit('offer-draw',{roomCode}):setStatus('Draw offer sent');const display=(n:number)=>`${Math.floor(Math.max(0,n)/60).toString().padStart(2,'0')}:${(Math.max(0,n)%60).toString().padStart(2,'0')}`;
 const blackView=color==='b';
 return <View style={styles.root}><SafeAreaView style={styles.safe}><View style={styles.top}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹</Text></Pressable><View><Text style={styles.player}>CHECKMATE</Text><Text style={styles.small}>{online?`Online • ${timeControl.label}`:bot?'Bot Match • 10+0':'Local • Rapid 10+0'}</Text></View><Pressable onPress={()=>router.replace('/play')}><Text style={styles.reset}>⌂</Text></Pressable></View>
 {online&&<View style={styles.room}><Text style={styles.roomText}>{roomCode?'ROOM '+roomCode:'Connecting…'}</Text><Text style={styles.roomHint}>{waiting?'Share this code with the opponent':'LIVE MATCH'}</Text></View>}
 <View style={styles.opponent}><Text style={styles.name}>{bot?'🤖 Checkmate Bot':color==='w'?'Black • Opponent':'White • Opponent'}</Text><Text style={styles.clock}>{display(color==='w'?clocks.b:clocks.w)}</Text></View>
 <View style={styles.board}>{Array.from({length:8},(_,displayRow)=>{const r=blackView?7-displayRow:displayRow;return Array.from({length:8},(_,displayCol)=>{const c=blackView?7-displayCol:displayCol;const p=board[r][c];const sq=String.fromCharCode(97+c)+(8-r);const dark=(r+c)%2===1;return <Pressable key={sq} onPress={()=>tap(sq)} style={[styles.square,{backgroundColor:dark?DARK:LIGHT},selected===sq&&styles.selected]}><Text style={[styles.piece,p?.color==='w'?styles.whitePiece:styles.blackPiece]}>{p?PIECES[p.color==='w'?p.type.toUpperCase():p.type]:''}</Text>{legal.includes(sq)&&<View style={styles.dot}/>}</Pressable>})})}</View>
 <View style={styles.you}><Text style={styles.name}>You • {color==='w'?'White':'Black'}</Text><Text style={[styles.clock,styles.activeClock]}>{display(color==='w'?clocks.w:clocks.b)}</Text></View><View style={styles.gamebar}><Text style={styles.status}>{status}</Text><Text style={styles.captured}>{online?'Realtime':'Moves'} {history.length}</Text></View><View style={styles.actions}><Action text="🤝 Draw" onPress={draw}/><Action text="⚑ Resign" onPress={resign}/><Action text="↻ Rematch" onPress={()=>router.replace(bot?'/game?bot=1':'/game')}/></View><ScrollView style={styles.moves} horizontal showsHorizontalScrollIndicator={false}>{history.map((m,i)=><Text key={i} style={styles.move}>{i+1}. {m}</Text>)}</ScrollView>
 </SafeAreaView></View>}
function Action({text,onPress}:{text:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={styles.action}><Text style={styles.actionText}>{text}</Text></Pressable>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:BG},safe:{flex:1,paddingHorizontal:12},top:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:WHITE,fontSize:38,lineHeight:38},reset:{color:WHITE,fontSize:24},player:{color:WHITE,fontWeight:'900',fontSize:14},small:{color:MUTED,fontSize:10,marginTop:2},room:{backgroundColor:'#10263a',borderRadius:12,padding:10,marginBottom:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},roomText:{color:ACCENT,fontWeight:'900',letterSpacing:1},roomHint:{color:MUTED,fontSize:10},opponent:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:CARD,borderRadius:12,padding:10,marginBottom:8},name:{color:WHITE,fontWeight:'800'},clock:{color:WHITE,fontSize:18,fontWeight:'900'},activeClock:{color:ACCENT},board:{width:'100%',aspectRatio:1,flexDirection:'row',flexWrap:'wrap',borderRadius:4,overflow:'hidden'},square:{width:'12.5%',height:'12.5%',alignItems:'center',justifyContent:'center'},selected:{borderWidth:3,borderColor:ACCENT},piece:{fontSize:34,textShadowColor:'#000',textShadowOffset:{width:1,height:1},textShadowRadius:2},whitePiece:{color:'#fff'},blackPiece:{color:'#111'},dot:{position:'absolute',width:10,height:10,borderRadius:5,backgroundColor:'rgba(0,0,0,.25)'},you:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:CARD,borderRadius:12,padding:10,marginTop:8},gamebar:{flexDirection:'row',justifyContent:'space-between',paddingVertical:10},status:{color:ACCENT,fontWeight:'900'},captured:{color:MUTED,fontSize:12},actions:{flexDirection:'row',gap:8},action:{flex:1,backgroundColor:CARD,borderRadius:10,paddingVertical:11,alignItems:'center'},actionText:{color:WHITE,fontSize:11,fontWeight:'800'},moves:{marginTop:8,maxHeight:42},move:{color:MUTED,fontSize:12,marginRight:14,paddingVertical:8}});
